title: How you can solve for Clue 3 in Game 3 of the #ALXchallenge2022
email: solomonaau188@gmail.com
twitter_username: solomonaau188
github_username: soloalx
author: Solomon Kebede
google_analytics: G-EHKYZHV2M1